### ISSUE TITLE
 Benefits 

### ISSUE THREAD

**Issue by Justdigit** [manniefesto/neptune-2-firmware#10]
I am sorry to ask here......I have a question What are the benefits for this firmware.
Does auto bed level works better?
Thanks

**Comment by manniefesto** [comment]
Hi, as stock there are no real benefits, except you will get the latest version of Marlin.

The idea of this repo is to give people the option of using some of the other Marlin functionality. Elegoo only give out the firmware to people when then request it via the support team, in other words there are no published versions of the stock firmware source code. 

This repo is a copy of the stock firmware that has had it's Marlin version updated. I asked for the firmwre from Elegoo so I could enable filament change (m600) as it does not work with the Neptune 2 out of the box, since then I have also enabled manual mesh leveling.

I dont have a ABL sensor, so I can't comment if the ABL integration is any better in this new Marlin version.

I hope this helps answer your question
